### ISSUE TITLE
Feedback on the Repository Setup

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/NextJSTemplate#12]
### Problem

The current NextJS Template repository contains the following elements that will serve as the basis for the Spezi Template Web Dashboard and other non-Spezi-related projects:
- Automated tests + code coverage report using https://jestjs.io/ & codecov
- Automated Documentation Deployment using https://typedoc.org/
- Automated deployment of the Next.js app to GitHub pages: https://spezi.health/SpeziTemplateWebDashboard/
- Linting and a way to fix errors locally using ESLint and prettier.
- REUSE specification conformance
- Docker files and a docker compose setup
- An automated setup to push the docker images to the GitHub docker hub: https://github.com/StanfordSpezi/SpeziTemplateWebDashboard/pkgs/container/spezitemplatewebdashboard
- Local smaller npm packages that can be used to develop the packages in a modular fashion; you can add as many as you want in the packages/* folder and then just need to make slight adjustments to add them to where they are currently referenced.

### Solution

It would be great to get feedback on the current setup and how we can improve it.

This mainly relates to these areas:
- Number of configuration files: It would be great to see if we can condense the number of configuration files. Compared to a Swift Package that only contains a few root-level configuration files, a Node/NextJS/React/npm setup seems to ask for a new configuration file for every small task ...
- Local package TS to JS conversion. The current setup is not ideal, as the local dependencies have to be explicitly mentioned in the main package.json file as `pre` steps for some of their elements so they are correctly transformed into JS representations. It would be great to see if we can automatize the setup.
- Documentation representation: It seems like typedoc does not properly resolve the root title of the project and seems to struggle with light/dark mode representations of images. Somehow, styling the docs to look nicer would also be great.
- Test coverage: It seems like only the main /app folder is covered using the test coverage setup. It would be great if we could explore how to also record coverage for the /packages.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@vishnuravi @Supereg @ckunchur Would be great to get our input and feedback on the current setup. Not ideal but I think that we are already on a good track. Some more eyes looking at the challenges and providing insights on the setup would definitely help!

**Comment by vishnuravi** [comment]
> @vishnuravi What type of CSS setup should we use, would be great to discuss this here.

I think we should use [Tailwind CSS](https://tailwindcss.com/). It is widely used, well-maintained, and [recommended in the Next.js documentation](https://nextjs.org/docs/app/building-your-application/styling/tailwind-css). PR #13 adds Tailwind to the project.

**Comment by PSchmiedmayer** [comment]
Thank you @vishnuravi; I just reviewed and merged the PR. 

It would be amazing if you have a good idea or suggestions on how to address some of the other issues noted above 👍
